import { NextResponse } from 'next/server'
import { revalidatePath } from 'next/cache'
import { client } from '@/sanity/lib/client'
import { writeClient } from '@/sanity/lib/writeClient'
import { generateInsights, type GeneratedArticle } from '@/lib/insights/generate'
import { sectionsToPortableText } from '@/lib/insights/portableText'
import { signUnpublish } from '@/lib/insights/unpublishToken'
import { notifyInsights, type PublishedItem } from '@/lib/insights/notify'

export const dynamic = 'force-dynamic'
export const maxDuration = 300 // web search + thinking can run for minutes

const CONFIDENCE_THRESHOLD = 0.7
const MIN_SOURCES = 3

function authorized(req: Request): boolean {
  const secret = process.env.CRON_SECRET
  if (!secret) return false
  const header = req.headers.get('authorization')
  return header === `Bearer ${secret}`
}

/** Publish-quality gate: real cited sources + confident + not a duplicate. */
function passesGate(a: GeneratedArticle, existingSlugs: Set<string>): boolean {
  const validSources = a.sources.filter((s) => /^https?:\/\//.test(s.url ?? ''))
  return (
    a.confidence >= CONFIDENCE_THRESHOLD &&
    validSources.length >= MIN_SOURCES &&
    !existingSlugs.has(a.slug)
  )
}

export async function GET(req: Request) {
  if (!authorized(req)) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }
  // Paused 26 Sep 2026: the writer's prompt predates the POPIA-safe positioning.
  // Nothing publishes until the prompt is rewritten and INSIGHTS_CRON_ENABLED=true is set.
  if (process.env.INSIGHTS_CRON_ENABLED !== 'true') {
    return NextResponse.json({ skipped: 'Insights writer paused (INSIGHTS_CRON_ENABLED is not "true")' })
  }
  if (!process.env.SANITY_API_WRITE_TOKEN || !process.env.ANTHROPIC_API_KEY) {
    return NextResponse.json(
      { error: 'Missing SANITY_API_WRITE_TOKEN or ANTHROPIC_API_KEY' },
      { status: 500 },
    )
  }

  const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://maruonline.com'

  // Existing posts (published + drafts) — dedupe against both.
  const existing = await client.fetch<{ slug: string; title: string }[]>(
    `*[_type == "post" && defined(slug.current)]{ "slug": slug.current, title }`,
  )
  const existingSlugs = new Set(existing.map((e) => e.slug))
  const existingTitles = existing.map((e) => e.title)

  let drafts: GeneratedArticle[]
  try {
    drafts = await generateInsights({ count: 1, existingTitles })
  } catch (err) {
    console.error('generateInsights failed:', err)
    return NextResponse.json(
      { error: 'Generation failed', detail: String(err) },
      { status: 502 },
    )
  }

  const results: PublishedItem[] = []

  for (const a of drafts) {
    const publish = passesGate(a, existingSlugs)
    const baseId = `insight-${a.slug}`
    const _id = publish ? baseId : `drafts.${baseId}`

    const doc = {
      _id,
      _type: 'post',
      title: a.title,
      slug: { _type: 'slug', current: a.slug },
      category: a.category,
      excerpt: a.excerpt,
      readTime: a.readTime,
      body: sectionsToPortableText(a.body),
      sources: a.sources.map((s) => ({
        _type: 'object',
        _key: Math.random().toString(36).slice(2, 12),
        title: s.title,
        url: s.url,
      })),
      autoGenerated: true,
      // Published only when it clears the gate; drafts carry no publishedAt.
      ...(publish ? { publishedAt: new Date().toISOString() } : {}),
    }

    await writeClient.createOrReplace(doc)
    existingSlugs.add(a.slug)

    const viewUrl = publish
      ? `${siteUrl}/insights/${a.slug}`
      : `https://www.sanity.io/manage`
    const unpublishUrl = publish
      ? `${siteUrl}/api/insights/unpublish?id=${encodeURIComponent(baseId)}&token=${signUnpublish(baseId)}`
      : undefined

    results.push({
      title: a.title,
      status: publish ? 'published' : 'draft',
      viewUrl,
      unpublishUrl,
    })
  }

  // Refresh the live Insights list for any new published post.
  if (results.some((r) => r.status === 'published')) {
    revalidatePath('/insights')
  }

  await notifyInsights(results)

  return NextResponse.json({
    ran: true,
    generated: drafts.length,
    published: results.filter((r) => r.status === 'published').length,
    drafted: results.filter((r) => r.status === 'draft').length,
    items: results.map((r) => ({ title: r.title, status: r.status })),
  })
}
